CREATE DATABASE crud_usuarios;
USE crud_usuarios;

CREATE TABLE usuarios (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	telefone VARCHAR(20),
	criado_em DATETIME DEFAULT CURRENT_TIMESTAMP()
);